app:
  datasource:
    source-default:
      url: jdbc:postgresql://localhost:5432/postgres1?currentSchema=demo
      username: postgres1
      password: 123
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 11
    source-one:
      url: jdbc:postgresql://localhost:5433/postgres2?currentSchema=demo
      username: postgres2
      password: 123
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 12
    source-two:
      url: jdbc:postgresql://localhost:5434/postgres3?currentSchema=demo
      username: postgres3
      password: 123
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 13